# create a list of sporulation gene (derived from the sporewise database:
# http://sporeweb.molgenrug.nl/index.php, https://doi.org/10.1093/nar/gkt1007)

spo_genes <- c("alr", "amyX", "cdaS", "cgeD", "cgeE", "cmpA", "codY", "cotI",
               "cotY", "cydA", "cydB", "cydC", "cydD", "cysE", "cysS", "dhaS",
               "fadM", "gltX","hemAT", "hemZ", "hmp", "hom", "ispH", "lplD",
               "lytH", "med", "miaA", "mstX", "murAA", "nadA", "nrnB", "ogt",
               "phrH", "pksD", "rghR", "ripX", "rnr", "ruvA", "smpB", "sndC",
               "spoIIIE", "SpoIIIJ", "spoIISA", "spoVS", "sprA", "sprB", "spsA",
               "spsB", "spsC", "spsD", "spsE", "spsF", "spsL", "spsM", "tepA",
               "thrB", "thrC", "tuaA/1", "tuaA/2", "tuaB", "tuaC", "tuaD",
               "tuaE", "uxaA", "yaaC", "yabS", "ybeF", "ybfA", "ybfB", "ycgH",
               "yczM", "yczN", "ydhU/1", "ydhU/2", "ydjO", "ydzH", "ydzR",
               "yetO", "yezF", "yfkS", "yfkT", "yflN", "yfmA", "ygzC", "yhdB",
               "yheF", "yhfA", "yhfC", "yhfN", "yhjQ", "yhzF", "yisL", "yisY",
               "yizC", "yizD", "yjaZ", "yjdB", "yjnA", "yjzC", "yjzK", "ykjA",
               "ykkA", "ykkB", "ykoN", "ykoP", "ykuC", "ykuS", "ykzE", "ykzP",
               "ykzQ", "ykzR", "ykzV", "ylzJ", "yndM", "yngL", "ynzE", "ynzL",
               "yoaM", "yoaQ", "yoyB", "yoyE", "yoyF", "yoyG", "yozT", "ypeP",
               "yppC", "yppG", "ypuI", "ypzD", "ypzG", "ypzH", "ypzI", "yqaO",
               "yqeC", "yqgT", "yqgU", "yqhO", "yqhP", "yqhR", "yqjB", "yqjC",
               "yqxA", "yqzK", "yqzO", "yrdA", "yrdD/1", "yrdD/2", "yrzM",
               "yrzN", "yrzP", "yrzQ", "yrzR", "ytaB", "ytaF", "ytaG", "ythA",
               "ythB", "ytkC", "ytzH", "ytzL", "yufS", "yugF", "yugO", "yugS",
               "yukJ", "yumB", "yusN", "yutG", "yutH", "yuzL", "yuzM", "yvaC",
               "yvaG", "yvaK", "ywaF", "ywbA", "ywbB", "ywhL", "ywkB", "ywlB",
               "ywlC", "ywlD", "ywlE", "ywlF", "ywlG", "ywnG", "ywoD", "yxkO",
               "yycE", "yycR", "yyzB", "abbA", "ccpC", "ykuJ", "ykuK", "ykuL",
               "abn2", "abrB", "accA", "accD", "acoC", "acoA", "acoB", "acoL",
               "albA", "alkA", "amyE", "antE", "appD", "appB", "appC", "appF",
               "aprE", "aprX", "arsR", "arsB", "arsC", "yqcK", "asnH", "yxaM",
               "yxbA", "yxbB", "yxnB", "asnO", "azoR2", "bacA", "bacB", "bacC",
               "bacD", "bacE", "bacF", "bdbB", "bdbA", "sunS", "sunT", "bdbC",
               "bdbD", "bdhA", "besA", "bofA", "bofC", "bpsA", "ypbQ", "bsaA",
               "ypgQ", "ypgR", "cccA", "ccdA", "ccpB", "exoA", "cgeA", "cgeB",
               "cgeC", "cheA", "cheB", "cheC", "cheD", "cheW", "cheY", "citG",
               "citH", "comER", "comK", "comZ", "cotA", "cotB", "ywrJ", "cotC",
               "cotD", "cotE", "cotF", "cotG", "cotH", "cotJA", "cotJB",
               "cotJC", "yesJ", "yesK", "cotM", "cotO", "cotQ", "cotR", "cotS",
               "cotSA", "ytxO", "cotT", "cotU", "cotV", "cotW", "cotX", "cotZ",
               "coxA", "safA", "csbX", "csfG", "csgA", "ybxH", "csn", "cspR",
               "ctaA", "ctaC", "ctaB", "ctaD", "ctaE", "ctaF", "ctaG", "ctaO",
               "ctpA", "ctpB", "cwlC", "cwlD", "cwlH", "cwlJ", "cwlS", "cypA",
               "cypX", "yvmC", "dacB", "spmA", "spmB", "dacF", "sigF", "spoIIAA",
               "spoIIAB", "dapG", "asd", "dapA", "spoVFA", "spoVFB", "dhbA",
               "dhbB", "dhbC", "dhbE", "dhbF", "disA", "divIB", "divIVA", "dltA",
               "dltB", "dltC", "dltD", "dltE", "dnaA", "dnaN", "dnaG", "sigA",
               "yqxD", "epr", "epsA", "epsB", "epsC", "epsD", "epsE", "epsF",
               "epsG", "epsH", "epsI", "epsJ", "epsK", "epsL", "epsM", "epsN",
               "epsO", "fabL", "mutY", "sspE", "ygaB", "flgB", "flgC", "flgE",
               "flhA", "flhB", "flhF", "fliE", "fliF", "fliG", "fliH", "fliI",
               "fliJ", "fliK", "fliL", "fliM", "fliP", "fliQ", "fliR", "fliY",
               "fliZ", "sigD", "swrB", "ylxF", "ylxG", "ylxH", "flgM", "ftsA",
               "ftsZ", "ftsE", "ftsX", "ftsY", "rnc", "smc", "galM", "dacC",
               "gcvT", "gcvPA", "gcvPB", "gdh", "glcU", "gerAA", "gerAB",
               "gerAC", "gerBA", "gerBB", "gerBC", "gerD", "gerE", "gerKA",
               "gerKB", "gerKC", "gerKD", "gerM", "gerPA", "gerPB", "gerPC",
               "gerPD", "gerPE", "gerPF", "gerQ", "gerR", "gerT", "gerW", "gin",
               "glgB", "glgA", "glgC", "glgD", "glgP", "glnH", "glnM", "glnP",
               "glnQ", "glpD", "glpF", "glpK", "gltP", "gmuA", "gmuB", "gmuC",
               "gmuD", "gmuE", "gmuF", "gmuG", "gmuR", "gntK", "gntP", "gntR",
               "gntZ", "gpr", "spoIIP", "guaC", "hag", "hbs", "hfq", "ispE",
               "kapB", "kapD", "katX", "kbaA", "kinA", "kinB", "kinC", "kinD",
               "kinE", "kipA", "kipI", "kipR", "ksgA", "ldt", "lgt", "lip",
               "lipC", "lonB", "lrpA", "lrpB", "lutA", "lutB", "lutC", "lytD",
               "lytE", "malL", "mdxE", "mdxF", "mdxG", "pgcM", "yvdE", "yvdF",
               "yvdJ", "yvdK", "mbl", "clpC", "mcsB", "mcsA", "metS", "mgtE",
               "minC", "minD", "mmgA", "mmgB", "mmgC", "mmgD", "mmgE", "yqiQ",
               "mpr", "ybfJ", "murB", "murG", "mutTA", "nfo", "yqfU", "nfrA",
               "ywcH", "nprE", "ntdR", "nucB", "oppA", "oppB", "oppC", "oppD",
               "oppF", "opuD", "oxdD", "patA", "patB", "pbpF", "pbpG", "pbpH",
               "pbpI", "pbpI", "yrrS", "pdaA", "pdaB", "pdp", "dra", "nupC",
               "pdxS", "pdxT", "pepF", "phoA", "phoB", "ydhF", "phoP", "phoR",
               "phrA", "rapA", "phrC", "phrE", "phrF", "phrG", "phrI", "phrK",
               "rapK", "phy", "pnbA", "ppiB", "ppsA", "ppsB", "ppsC", "ppsD",
               "ppsE", "prkA", "prkC", "prkD", "proH", "proJ", "pspA", "ydjG",
               "ydjH", "ydjI", "ptkA", "ptpZ", "tkmA", "ugd", "pucH", "putB",
               "putC", "putP", "qcrA", "qcrB", "qcrC", "racA", "rapB", "rapE",
               "rapG", "rapH", "rbsA", "rbsB", "rbsC", "rbsD", "rbsK", "rbsR",
               "remA", "rgaR", "ribH", "rocA", "rocB", "rocC", "rocD", "rocE",
               "rocF", "rocG", "rok", "rsfA", "rsiW", "sigW", "sbp", "scoC",
               "albB", "albC", "albD", "albE", "albF", "albG", "sboA", "sboX",
               "sda", "sdpA", "sdpB", "sdpC", "sdpI", "sdpR", "sepF", "ylmD",
               "ylmE", "ylmG", "ylmH", "sigE", "spoIIGA", "sigG", "sigH",
               "sinI", "sinR", "sirA", "yneF", "skfA", "skfB", "skfC", "skfE",
               "skfF", "skfG", "skfH", "sleB", "ypeB", "slrR", "soj", "spo0J",
               "splA", "splB", "spo0A", "spo0B", "obg", "spo0E", "spo0F", "spo0M",
               "spoIIB", "spoIID", "spoIIE", "spoIIIAA", "spoIIIAB", "spoIIIAC",
               "spoIIIAD", "spoIIIAE", "spoIIIAF", "spoIIIAG", "spoIIIAH",
               "spoIIIC", "spoIVCB", "spoIIIG", "jag", "spoIIM", "spoIIQ",
               "spoIIR", "spoIISB", "spoIVA", "spoIVB", "spoIVCA", "spoIVFA",
               "spoIVFB", "spoVAA", "lysA", "spoVAB", "spoVAC", "spoVAD",
               "spoVAE", "spoVAF", "spoVAEA", "spoVAEB", "spoVB", "spoVD",
               "spoVE", "spoVG", "spoVID", "ysxE", "spoVIF", "spoVK", "spoVM",
               "spoVR", "spoVT", "spsG", "spsI", "spsJ", "spsK", "sqhC", "sodF",
               "sscA", "sspA", "sspB", "sspC", "sspD", "sspF", "sspG", "yurS",
               "sspH", "acoR", "sspI", "sspJ", "sspK", "sspL", "sspM", "sspN",
               "tlp", "sspO", "sspP", "stoA", "ykvU", "subA", "sunA", "surC",
               "tapA", "sipW", "tasA", "tgl", "thyA", "tkt", "tlpA", "mcpA",
               "tuaF", "tuaG", "tuaH", "ureA", "ureB", "ureC", "usd", "spoIIID",
               "uxaB", "uxuA", "vpr", "xynC", "xynD", "yaaH", "yaaT", "yabG",
               "yabP", "divIC", "yabQ", "yabR", "yabT", "ybaJ", "ybaK", "ybaK",
               "ybaS", "ybbC", "ybdN", "ybdO", "ybfO", "ybfP", "ycbJ", "ycbC",
               "ycbD", "ycbE", "ycbF", "ycbG", "ycbH", "ycdA", "ycgF", "ycgG",
               "ycgI", "ycgL", "yckC", "yckD", "yclF", "yclG", "ycnK", "ycsN",
               "ydbI", "ydcA", "ydcC", "ydcI", "ydcP", "yddJ", "yddT", "ydeH",
               "ydeJ", "ydfR", "ydfS", "ydgB", "cotP", "ydgA", "ydhD", "yeaA",
               "ydjP", "yebD", "yeeK", "yerB", "yerC", "yerI", "yesL", "yesM",
               "yetF", "yfhD", "yfhE", "yfhF", "yfhM", "yfhP", "yfhS", "yfjC",
               "yfkD", "chaA", "yfkO", "yfkQ", "yfkR", "yflA", "yflB", "yflJ",
               "yfmB", "yfmG", "yfmH", "yfmI", "yfmJ", "yfnD", "yfnE", "yfnF",
               "yfnG", "yfnH", "ygaK", "ygzA", "yhaL", "yhaM", "yhaP", "yhaQ",
               "yhaR", "yhaS", "yhaT", "yhaX", "yhbA", "yhbB", "yhbH", "yhbJ",
               "yhcA", "yhcB", "yhcC", "yhcJ", "yhcM", "yhcN", "yhcO", "yhcQ",
               "yhcR", "yhcS", "yhcT", "yhcV", "yhcY", "yhcZ", "yhdC", "yheC",
               "yheD", "yheI", "yheJ", "yhfM", "yhfO", "yhfW", "yhjL", "yhjR",
               "yhxC", "yisI", "yisJ", "yisK", "yisN", "yisP", "yisT", "yitB",
               "yisZ", "yitA", "yitC", "yitD", "yitE", "yitF", "yitG", "yitQ",
               "yjaU", "yjaV", "yjbA", "yjbE", "yjbO", "yjcA", "yjcM", "yjcZ",
               "yjdG", "yjdH", "yjfA", "yjiA", "yjmC", "exuR", "exuT", "yjmD",
               "yjmF", "yjqC", "yjzB", "ykaA", "pit", "yknT", "yknU", "yknV",
               "yknW", "yknX", "yknY", "yknZ", "ykoF", "thiV", "thiW", "thiX",
               "ykoM", "ykoQ", "ykoS", "ykoT", "ykoV", "ykoU", "ykoW", "ykoY",
               "ykpC", "ykuU", "ykuV", "ykvI", "ykvP", "ykvQ", "ykwB", "ykzD",
               "ykzH", "ykzI", "ylaE", "ylaJ", "ylaK", "ylaM", "ylbA", "ylbB",
               "ylbC", "ylbD", "ylbE", "ylbF", "ylbJ", "ylbK", "ylmC", "yloB",
               "yloS", "ylqB", "ylxW", "ylxX", "ylxY", "mlpA", "ylyA", "ymaD",
               "ymaE", "ymzB", "ymaF", "ymaG", "ymcA", "ymdB", "rny", "ymfD",
               "ymfI", "ymfJ", "ymxH", "ynaD", "yncD", "yncE", "yncM", "yndA",
               "yndD", "yndE", "yndF", "yndL", "ynfE", "yngHB", "yngJ", "yngE",
               "yngF", "yngG", "yngH", "yngI", "yngK", "ynzB", "ynzD", "yoaI",
               "yoaR", "yozF", "yoaW", "yobB", "yobN", "yobO", "yobW", "yocD",
               "yocH", "yocL", "yocM", "yodH", "yodI", "yodL", "yodN", "yodT",
               "kamA", "yodP", "yodQ", "yodR", "yodS", "yokU", "yodU", "yoeA",
               "yojB", "yojC", "yojK", "yokI", "yokJ", "yokK", "yokL", "yolA",
               "yolB", "yolC", "yomJ", "yoqM", "yorD", "yotN", "yozD", "yozE",
               "yozN", "yocN", "yozQ", "ypbG", "ypbH", "ypeQ", "ypfB", "yphA",
               "seaA", "yphE", "yphF", "ypiA", "ypiB", "ypiF", "ypjB", "yppD",
               "yppE", "ypqA", "ypqP", "yptA", "ypuD", "ypzA", "ypzC", "yqaB",
               "yqaN", "yqaP", "yqcF", "yqcG", "yqcI", "yqeW", "yqfC", "yqfD",
               "yqfQ", "yqfT", "yqfX", "yqfZ", "ispG", "yqgE", "yqgO", "yqhH",
               "yqhG", "yqhQ", "yqhV", "yqxI", "yqxJ", "yqzC", "yqzD", "yqzG",
               "yraG", "adhB", "yraD", "yraE", "yraF", "yrbD", "yrbG", "yrhA",
               "yrkC", "yrkD", "yrpC", "yrpD", "yrrD", "yrrI", "yrrL", "yrvJ",
               "yrzA", "yrzE", "yrzI", "yrzK", "yscB", "ysfB", "yslB", "ysmB",
               "racE", "ysnB", "ysnD", "ysnE", "ytcA", "ytcB", "ytcC", "ytdA",
               "yteA", "yteT", "yteV", "ytfI", "ytlA", "ytlC", "ytlD", "ytlR",
               "ytrH", "ytrI", "yttP", "ytvB", "ytvI", "ytwI", "ytxC", "ytxG",
               "ytxH", "ytxJ", "ytzC", "yuaB", "yubC", "yueE", "yueG", "yugT",
               "yuiC", "yunB", "yunC", "yurI", "yurZ", "yusD", "yusE", "yusR",
               "yusW", "yutC", "yutJ", "yuxH", "yuxL", "yuzA", "yuzC", "yuzE",
               "yuzF", "yvbH", "yvcA", "yvcB", "yvzA", "yvdO", "yvdQ", "yveA",
               "yvgN", "yvgO", "yvnA", "yvnB", "yvqJ", "yvrN", "yvrO", "yvrP",
               "yvyD", "yvyE", "tagV", "ywbD", "ywbF", "ywcB", "ywcA", "ywcE",
               "ywdC", "yweA", "ywhK", "ywjE", "ywjD", "ywkF", "ywmA", "ywnF",
               "ywnH", "ywnJ", "ywoC", "ywoF", "ywrK", "yxaA", "yxaB", "yxaJ",
               "yxaL", "yxbC", "yxbD", "yxeD", "yxeE", "yxjC", "scoA", "scoB",
               "yxjF", "yxkD", "yxzE", "yyaC", "yyaD", "yyaL", "yyaO", "yybI",
               "yybN", "yybP", "yycN", "yycO", "yycP", "yycQ", "yydF", "yydG",
               "yydH", "yydI", "yydJ", "yyxA")

# And of synonyms for the genes in the above list

spo_synonyms <- c("yvaN", "spo0J87", "yokA", "yotN", "yodU", "ypqP", "ykzF",
                  "ykuM", "yxiA", "abnB", "cpsX", "tolB", "yttI", "yfjI",
                  "yfjK", "yfjJ", "yfjH", "ywiA", "amyA", "sprE", "sprE",
                  "yqcJ", "yqcL", "yqcM", "yxaN", "yxaO", "aslA", "yxaP",
                  "yisO", "yucB", "yvaB", "yvaB", "ywfB", "ipa-80d", "ywfC",
                  "ipa-81d", "ywfD", "ipa-82d", "ywfE", "ipa-83d", "ywfF",
                  "ipa-84d", "ywfG", "ipa-85d", "yolK", "yolI", "yolH",
                  "yvgU", "yvgV", "ydjL", "yuiI", "bcsA", "bpsB", "yyaG",
                  "yojJ", "cgeAA", "cgeAB", "cgeBA", "cgeBA", "cgeBB",
                  "cgeBC", "cheN", "cheL", "ylxJ", "ylxK", "cheB", "yxiQ",
                  "comD", "comED", "yjzA", "yjaW", "pig", "pig", "ywrH",
                  "ywrH", "ytaA", "yeeN", "yfxC", "yfxD", "yeeN", "yfxC",
                  "yfxD", "yneL", "yjbX", "yvdP", "yvdO", "ytxN", "ytbA",
                  "ytbB", "ynzH", "yrbB", "yrbA", "yjdK", "yzbD", "yvjB",
                  "yvjB", "yqeE", "ycbQ", "yojL", "yrdE", "ypuJ", "ypuK",
                  "spoIIAC", "lssD", "dpaA", "dpaB", "entA", "entE", "yacK",
                  "dds", "tms-12", "ylmJ", "ipa-5r", "dae", "ipa-4r", "ipa-3r",
                  "ipa-2r", "ipa-1r", "dnaH", "dnaJ", "dnaK", "dnaG", "dnaK",
                  "dnaE", "rpoD", "crsA", "yqfM", "dnaG", "dnaK", "dnaH",
                  "dnaJ", "dnaK", "ipa-15r", "yveK", "yveK", "yveL", "yveL",
                  "yveM", "yveM", "yveN", "yveN", "yveO", "yveO", "yveP",
                  "yveP", "yveQ", "yveQ", "yveR", "yveR", "yveS", "yveS",
                  "yveT", "yveT", "yvfA", "yvfB", "yvfA", "yvfB", "yvfC",
                  "yvfC", "yvfD", "yvfD", "yvfE", "yvfE", "yvfF", "yvfF",
                  "yfhR", "ygaA", "yfhR", "ygaA", "yfhQ", "yusM", "flgG",
                  "flaA15", "cheF", "cheD", "flaB", "ylxL", "flgD", "spoIIN",
                  "ts-1", "srb", "srb", "rncS", "ylqA", "yoxA", "pbp", "yqhK",
                  "gcvP", "ycxE", "ycxE", "yczF", "yisH", "yisH", "yisG",
                  "yisG", "yisF", "yisE", "yisE", "yisD", "yisC", "ywdL",
                  "ipa-62r", "ylbO", "yozR", "ytfJ", "csfB", "yaaM", "ydhN",
                  "ydhM", "ydhO", "ydhP", "ydhR", "ydhS", "ydhT", "ydhQ",
                  "yumD", "dbpA", "ymaH", "ykiA", "yabH", "ipk", "yugB",
                  "yxlI", "ybxC", "ybaM", "spoIIF", "spoIIJ", "gsiC", "scoB",
                  "scoD", "ssb", "ykvD", "ykrQ", "ycsJ", "ycsO", "ykuD",
                  "gerF", "yvoC", "lipA", "lipA", "ycsk", "ysxF", "yddO",
                  "yvfV", "yvfW", "yvbY", "cwlG", "papQ", "cwlF", "yunA",
                  "yutA", "yvdL", "yvdG", "yvdH", "yvdI", "yvdM", "mdxR",
                  "malK", "mdxK", "mecB", "yacI", "yacH", "ykok", "divIVB1",
                  "yqiL", "yqiM", "yqiN", "yqiO", "prpC", "yqiP", "prpD",
                  "prpB", "ylxC", "ytkD", "rppH", "yqfS", "ywcG", "ipa-43d",
                  "ipa-44d", "yhjM", "spo0KA", "spo0KB", "spo0KC", "spo0KD",
                  "spo0KE", "ytfQ", "yoaN", "uat", "ponA", "ywhE", "ykuA",
                  "yrrR", "yfjS", "ybaN", "deoC", "yaaD", "yaaE", "yjbG",
                  "phoAIV", "phoAIII", "gsiAB", "gsiAA", "spo0L", "ywhI",
                  "yycL", "yobG", "yodV", "yzxA", "estB", "cypBS", "yloP",
                  "ybdM", "yoxE", "yohA", "yohA", "ydjF", "ywqD", "ywqE",
                  "ywqC", "ywqF", "yunH", "ycgM", "ycgM", "ycgN", "ycgN",
                  "ycgO", "bfcA", "petC", "bfcB", "petB", "bfcC", "petD",
                  "ywkC", "spo0P", "ywmE", "yycM", "yeeH", "yzqA", "ylzA",
                  "ipa-76d", "ipa-77d", "ipa-78d", "argI", "ykuW", "ykuW",
                  "ywfN", "ybbM", "ybbL", "hpr", "catA", "ywhR", "ywhQ",
                  "ywhP", "ywhO", "ywhN", "ywhM", "sbo", "yvaW", "yvaX",
                  "yvaY", "yvaZ", "yvbA", "ylmF", "spoIIGB", "spoIIAC",
                  "spoIIIG", "spoIIIG", "spo0H", "sin", "flaD", "yneE",
                  "yoxF", "yoxG", "ybcO", "ybcP", "ybcQ", "ybcS", "ybdA",
                  "ybdB", "ybdD", "ybdE", "ypeA", "ypeA", "joeB", "yzuA",
                  "joeB", "yzuA", "yveJ", "slr", "spo0JA", "spo0JB", "ykxI",
                  "spl", "spo0C", "spo0G", "spoIIL", "sof-1", "spo0D", "ygaI",
                  "spoIIC", "spoIIH", "spoIIK", "sigK", "spoIVD", "spoIVE",
                  "cisB", "sigK", "sigG", "spo0J87", "yqeP", "ywnI", "cfsX",
                  "ykaC", "spoVP", "cisA", "bofB", "spoVL", "spoVAEA",
                  "spoVAEA", "spoIIIF", "yjcC", "spoVJ", "yabL", "ipa-63d",
                  "ipa-64d", "ipa-65d", "ipa-66d", "ipa-67d", "ipa-68d",
                  "ipa-69d", "spsH", "ipa-71d", "ipa-72d", "ipa-73d", "yhzE",
                  "yfjU", "yfjG", "yzcB", "ysfA", "cotK", "cotL", "spoIVH",
                  "ykvV", "fin", "yabK", "yolG", "yqhD", "yqxM", "yqhD", "yqxM",
                  "yqhE", "yqhE", "cotN", "yqhF", "cotN", "yqhF", "ymfB", "ylxI",
                  "yuxF", "yugV", "tktA", "yvhF", "yvhG", "yvhH", "ywqF", "yjmJ",
                  "yjmI", "yjmE", "ipa-45r", "ynfF", "ybxH", "ybxH", "yzbB",
                  "gudP", "gudD", "garD", "ydjQ", "yfnJ", "cypD", "yfkE", "natB",
                  "queG", "ygaP", "ygaQ", "yzdC", "brmC", "ndtA", "yucA", "yucD",
                  "yucH", "spoVIF", "yjmH", "yjmG", "ykaB", "cse15", "thiU",
                  "ykoE", "ykoD", "ykoC", "ykoR", "ligD", "thiN", "ymxI",
                  "ymxG", "ylmK", "ymdA", "alrB", "accC", "yotA", "csk22",
                  "yodO", "argE", "ypqP", "jofB", "yphB", "johF", "jopC",
                  "yqfY", "yqgE", "yqdE", "yqdF", "mccA", "glr", "yzwA",
                  "yzwB", "cse60", "csb40", "comB", "yufA", "cotR", "yvsB",
                  "yziB", "yvrM", "yviI", "yvhK", "yvhJ", "ipa-11d", "ipa-17d",
                  "ipa-19d", "ipa-21r", "ipa-32r", "ipa-31r", "ipa-41r",
                  "ipa-53r", "ipa-74d", "uvsE", "ipc-28d", "glxK", "yxaK",
                  "yxaQ", "yxaR", "yxjD", "yxjE", "yycK")


# Load in annotations, sporeweb gene database file, and Galperin et al., 2012 
# essential sporulation gene table 
ppenenog <- read.csv("PPEN.eggNOG.csv")
sporeweb <- read.csv("sporeweb_all_genes.csv")
galperin <- read.csv("Galperin_et_al_2012_essential_genes.csv")

# From Pasteruia eggNOG annotations pull out sporulation genes.
ppen_spor <- ppenenog[grep(paste(spo_genes, collapse = "|"),
                         ppenenog$Gene.name,
                         ignore.case = TRUE), ]
ppen_spor2 <- ppenenog[grep(paste(spo_synonyms, collapse = "|"),
                            ppenenog$Gene.name,
                            ignore.case = TRUE),]

all_pas_spor <- rbind(ppen_spor, ppen_spor2)

# combine Pasteuria annotations with the sporeweb db
merged <- merge(all_pas_spor, sporeweb, by="Gene.name")
# and with the Galperin et al., db.
merged <- merge(merged, galperin, by="Gene.name")

# look for missing genes judged marked essential by Galperin et al
essential <- galperin[galperin$Essen.tial. =="Y", ]
vague <- galperin[galperin$Essen.tial. =="Y/N", ]
non_essential <- galperin[galperin$Essen.tial. =="N", ]
blank <- c("", " ")
unknown <- galperin[galperin$Essen.tial. == "" | galperin$Essen.tial. == " ", ]

check <- setdiff(essential$Gene.name, all_pas_spor$Gene.name)
check


# Look for these genes in annotation free text
check_genes <- ppenenog[grep(paste(check, collapse = "|"),
                           ppenenog$eggNOG_description,
                           ignore.case = TRUE), ]
check_genes$eggNOG_description



